### ISSUE TITLE
建议把 AutoDSE 和 Merlin Compiler 直接打包在一起

### ISSUE THREAD

**Issue by Oxygen-Chu** [UCLA-VAST/AutoDSE#2]
建议把 AutoDSE 和 Merlin Compiler 直接打包在一起，一起编译一起配置。
Merlin Compiler 用的很多库都比较古老（AutoBridge 也有同样的问题，我也已经提交了 Issue），特别是 LLVM 好像只能用 6/7 版本（现在都 13/14 了），很不好编译，挑环境比较严重。

**Comment by comaniac** [comment]
Please use English.

This repo is mainly for the AutoDSE paper. By that time Merlin compiler hasn't been open source. Since Merlin is open source already, you could find the corresponding AutoDSE in the Merlin compiler repo as one of its component. Merlin and AutoDSE should work together without issues there.

**Comment by Oxygen-Chu** [comment]
I have checked the Merlin repo, but cannot find AutoDSE.
Here is where I checked in, is that a wrong place I entered?
https://github.com/Xilinx/merlin-compiler/tree/main/trunk

**Comment by comaniac** [comment]
Here: https://github.com/Xilinx/merlin-compiler/tree/main/trunk/optimizers/autodse, although it might be a bit diverge compared to this repo.

**Comment by atefehsz** [comment]
Thanks for the feedback. We will expand the description on AutoDSE's usability soon.
